version: 2
jobs:
  staging_api:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps-{{ checksum "~/repo/server/ansible/requirements.txt" }}
      - run:
          name: Install PIP Dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r ~/repo/server/ansible/requirements.txt
      - save_cache:
          key: deps-{{ checksum "~/repo/server/ansible/requirements.txt" }}
          paths:
            - "env"
      - run:
          name: Setup Ansible Vault pass
          command: |
            echo $VAULT_PASS | tee ~/repo/server/ansible/.vault-pass
      - run:
          name: Deploy with Ansible
          command: |
            . env/bin/activate
            cd ~/repo/server/ansible
            ansible-playbook -i hosts deploy.yml --limit staging_v1 --vault-password-file ~/repo/server/ansible/.vault-pass
  stress_api:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps-{{ checksum "~/repo/server/ansible/requirements.txt" }}
      - run:
          name: Install PIP Dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r ~/repo/server/ansible/requirements.txt
      - save_cache:
          key: deps-{{ checksum "~/repo/server/ansible/requirements.txt" }}
          paths:
            - "env"
      - run:
          name: Setup Ansible Vault pass
          command: |
            echo $VAULT_PASS | tee ~/repo/server/ansible/.vault-pass
      - run:
          name: Deploy with Ansible
          command: |
            . env/bin/activate
            cd ~/repo/server/ansible
            ansible-playbook -i hosts deploy.yml --limit stress_v1 --vault-password-file ~/repo/server/ansible/.vault-pass
  production_api:
    docker:
      - image: circleci/python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps-{{ checksum "~/repo/server/ansible/requirements.txt" }}
      - run:
          name: Install PIP Dependencies
          command: |
            python3 -m venv env
            . env/bin/activate
            pip install -r ~/repo/server/ansible/requirements.txt
      - save_cache:
          key: deps-{{ checksum "~/repo/server/ansible/requirements.txt" }}
          paths:
            - "env"
      - run:
          name: Setup Ansible Vault pass
          command: |
            echo $VAULT_PASS | tee ~/repo/server/ansible/.vault-pass
      - run:
          name: Deploy API with Ansible
          command: |
            . env/bin/activate
            cd ~/repo/ansible/server
            ansible-playbook -i hosts deploy.yml --limit production_v1 --vault-password-file ~/repo/server/ansible/.vault-pass
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - staging_api:
          filters:
            branches:
              only: ambassador-stage
      - stress_api:
          filters:
            branches:
              only: ambassador-stress
      - production_api:
          filters:
            branches:
              only: ambassador
