# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  deploy-to-coopernetes:
    docker:
      - image: colabcoop/coopernetes-deploy:0.4.2
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build api container
          command: /build-docker.sh
          environment:
            DOCKERFILE: server/Dockerfile
            DOCKER_CONTEXT: server
            DOCKER_REPO: colabcoop/hello-voter-api
      - run: /helmfile-apply.sh

workflows:
   deploy:
     jobs:
       - deploy-to-coopernetes:
           context: coopernetes-staging
