apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.image.tag }}
        name: neo4j
        {{- with .Values.image.env}}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        ports: ## Ports to map
            - containerPort: 7474
              name: http
            - containerPort: 7687
              name: bolt
            - containerPort: 7473
              name: https
        volumeMounts:
            - name: neo4j-logs
              mountPath: /logs
            - name: neo4j-data
              mountPath: /var/lib/neo4j/data
      volumes:
          - name: neo4j-data
            persistentVolumeClaim:
              claimName: {{ .Values.name }}-data
          - name: neo4j-logs
            persistentVolumeClaim:
              claimName: {{ .Values.name }}-logs
