kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: neo4j-db-claim
  labels:
    app: neo4j-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
