kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: neo4j-db-data
  labels:
    app: neo4j-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 20Gi
---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: neo4j-db-logs
  labels:
    app: neo4j-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 2Gi
