kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ .Values.name }}-data
  labels:
    app: {{ .Values.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 20Gi
---
kind: "PersistentVolumeClaim"
apiVersion: "v1"
metadata:
  name: {{ .Values.name }}-logs
  labels:
    app: {{ .Values.name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 2Gi
