apiVersion: v1
kind: Secret
metadata:
  name: hello-voter-secrets
type: Opaque
stringData:
  config.yaml: |-
    twilio_account_sid: {{ requiredEnv $TWILIO_ACCOUNT_SID }}
    twilio_auth_token: {{ requiredEnv $TWILIO_AUTH_TOKEN }}
    twilio_from: {{requiredEnv $TWILIO_FROM }}
    neo4j_password: {{requiredEnv $NEO4J_PASSWORD }}
