name: Android CI

on:
  push:
    branches: [ master ]
    paths:
      - 'client/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'client/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: (cd client && npm install && echo "GOOGLE_API_KEY_ANDROID=none" > .env && cd android && ./gradlew app:assembleDebug)
